/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

public class App {
    public static void main(String[] args) {
        // Easy88 inst = new Easy88();
        // int[] nums1 = { 1, 2, 3, 0, 0, 0 };
        // int[] nums2 = { 2, 5, 6 };
        // int m = 3;
        // int n = 3;
        // int[] nums1 = { 0 };
        // int[] nums2 = { 1 };
        // int m = 0;
        // int n = 1;
        // inst.merge(nums1, m, nums2, n);

        Easy27 inst = new Easy27();
        // int[] nums = { 0, 1, 2, 2, 3, 0, 4, 2 };
        // int val = 2;
        // int[] nums = { 3, 2, 2, 3 };
        // int val = 3;
        // int[] nums = { 1 };
        // int val = 1;
        int[] nums = { 4, 5 };
        int val = 5;
        inst.removeElement(nums, val);
    }
}
