/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

public class App {
    public static void main(String[] args) {
        PickQuestion pq = new PickQuestion();
        pq.pickQuestion(5);
    }
}
