/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;

import org.example.app.arrayOrString.Medium347;

class TestM47 {
    @Test
    void testM347_case1() {
        Medium347 instance = new Medium347();
        int[] nums = { 1, 1, 1, 2, 2, 3 };
        int k = 2;
        int[] ans = instance.topKFrequent(nums, k);
        int[] expected = { 1, 2 };

        assertArrayEquals(expected, ans);
    }

    @Test
    void testM347_case2() {
        Medium347 instance = new Medium347();
        int[] nums = { 1, 2, 1, 2, 1, 2, 3, 1, 3, 2 };
        int k = 2;
        int[] ans = instance.topKFrequent(nums, k);
        int[] expected = { 1, 2 };

        assertArrayEquals(expected, ans);
    }
}
